### ISSUE TITLE
[Feature Request]Dir for log

### ISSUE THREAD

**Issue by SteveLauC** [lunacookies/etcetera#17]
## Log dir for each platform

| Linux | macOS | Windows |
|----------|------------|---------------|
|`state_dir()`|`$HOME/Library/Logs/app_bundle_id`|`data_dir()`|

## Ref
* [Linux](https://stackoverflow.com/q/25897836/14092446)
* [macOS](https://stackoverflow.com/q/54456961/14092446)
* [Windows](https://stackoverflow.com/q/1572934/14092446)

**Comment by utkarshgupta137** [comment]
I know that `$XDG_STATE_DIR` is the suggested location for log files, but I can't find any official documentation mentioning the correct location for macOS or Windows (StackOverflow doesn't count). On my Mac, `~/Library/Logs` is used by some applications, but only a couple of them are from Apple itself - unlikely that it is the correct location. A Google search suggests that there is no consensus & each app stores it differently (cache_dir, data_dir, `~/Library/Logs`, & `~/Library/Containers` seem to be the most popular).

Also, if you look at the API right now, you'll see that etcetera doesn't return anything for `state_dir()` or `runtime_dir()` on Apple/Windows. This is because there is no good equivalent for them on those platforms & instead of etcetera suggesting an equivalent, it is up to the developer to decide where those files go. Suggesting `data_dir` or `~/Library/Logs` on our end doesn't seem like a good idea to me - IMO it makes it less useful.

Let me know what you think.

**Comment by SteveLauC** [comment]
Yeah I agree.

Log fir is not specified in the official doc(Even with XDG, people use state dir simply for the reason it is chosen by some famous apps).

Let's close this issue then.

**Comment by utkarshgupta137** [comment]
`$XDG_STATE_DIR` was added for these kinds of files only & the [XDG spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) explicitly mentions logs as one of the files which should go in the state dir.

**Comment by SteveLauC** [comment]
Thanks for showing me this, seems I should take another shot on that spec:)
